input:
  allowed_files:
  - .WAV
  - .wav
  - .mp3
  - .flac
  - .m4a
  limit_positives: 0 # 0 to disable. If set, this limits the number of positive vocalisations included in the synthetic dataset.
output:
  length: 10 #seconds
  n: 1000
  snr_range:
  - 0.1
  - 1
  val_ratio: 0.9 # for use with do_train_val_split: true
  highpass_variable: 0
  lowpass_variable: 0
  include_kaytoo: true # This setting is the only one to enable for use with classifier_small.py
  include_boxes: true
  include_masks: true
  include_spectrogram: true
  include_soundfile: false # 48000 Hz
  negative_overlay_range:
  - 0
  - 2
  positive_overlay_range:
  - 0
  - 2
  repetitions: # repetitions occur 50% of the time
  - 1
  - 3
  overwrite_output_path: true
  rainbow_frequency: false
  single_class: false
  concatenate: false
paths:
  dataset: example_dataset
  do_train_val_split: false
  negative: negative
  noise: noise
  output: augmented_dataset_output
  vocalisations: vocalisations
plot:
  color_filter: dusk # 'dusk' or None for true color
  toggle: false
  show_labels: false